[server]
headless = true
enableCORS = false
port = 8501

[theme]
base = "dark"
primaryColor = "#E2001A"
backgroundColor = "#0E1117"
secondaryBackgroundColor = "#262730"
textColor = "#FAFAFA"
font = "sans serif"
